ALTER TYPE "SmartphoneBrand" ADD VALUE IF NOT EXISTS 'TECNO';
ALTER TYPE "SmartphoneBrand" ADD VALUE IF NOT EXISTS 'INFINIX';

ALTER TYPE "SpeakerBrand" ADD VALUE IF NOT EXISTS 'BEATS';
ALTER TYPE "SpeakerBrand" ADD VALUE IF NOT EXISTS 'ULTIMATE_EARS';
ALTER TYPE "SpeakerBrand" ADD VALUE IF NOT EXISTS 'MARSHALL';
ALTER TYPE "SpeakerBrand" ADD VALUE IF NOT EXISTS 'SONOS';

ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'ONEPLUS';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'SONY';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'XIAOMI';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'SPIGEN';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'BELKIN';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'OTTERBOX';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'JBL';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'BEATS';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'BOSE';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'MOPHIE';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'CASETIFY';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'GOOGLE';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'UAG';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'JABRA';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'NOMAD';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'NOTHING';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'MOUS';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'SENNHEISER';
ALTER TYPE "AccessoryBrand" ADD VALUE IF NOT EXISTS 'RAVPOWER';
